USE QLDA
--bai 1
SELECT DEAN.TENDEAN,CAST(AVG(PHANCONG.THOIGIAN) AS decimal(10,2)) 
		FROM DEAN JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA
		GROUP BY DEAN.TENDEAN
SELECT DEAN.TENDEAN,CAST(AVG(PHANCONG.THOIGIAN) AS varchar) 
		FROM DEAN JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA
		GROUP BY DEAN.TENDEAN

SELECT REPLACE(CONVERT(decimal(10,2),AVG(NHANVIEN.LUONG)),'.',','), PHONGBAN.TENPHG 
	   FROM NHANVIEN 
	   JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	   GROUP BY TENPHG
SELECT TENPHG , 
	  LEFT(CAST(AVG(LUONG) AS varchar),3)+
	  REPLACE(CAST(AVG(LUONG) AS varchar),LEFT(CAST(AVG(LUONG) AS varchar),3),',')
	   FROM NHANVIEN 
	   JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	   GROUP BY TENPHG
---Bai2

SELECT  * FROM DEAN

SELECT * FROM PHANCONG

SELECT TENDEAN,CEILING(SUM(THOIGIAN))
	FROM PHANCONG JOIN  DEAN ON DEAN.MADA = PHANCONG.MADA
	GROUP BY TENDEAN

SELECT TENDEAN,FLOOR(SUM(THOIGIAN))
	FROM PHANCONG JOIN  DEAN ON DEAN.MADA = PHANCONG.MADA
	GROUP BY TENDEAN
SELECT TENDEAN,ROUND(SUM(THOIGIAN),2)
	FROM PHANCONG JOIN  DEAN ON DEAN.MADA = PHANCONG.MADA
	GROUP BY TENDEAN
--c1
DECLARE @avgLuong float;
SELECT @avgLuong = ROUND(AVG(LUONG),2)
	FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG 
	WHERE TENPHG like N'Nghiên Cứu'
SELECT HONV , TENLOT, TENNV ,LUONG FROM NHANVIEN WHERE LUONG >@avgLuong
--c2
SELECT HONV , TENLOT, TENNV ,LUONG 
	FROM NHANVIEN 
	WHERE LUONG > (SELECT ROUND(AVG(LUONG),2)
	FROM NHANVIEN JOIN PHONGBAN 
	ON NHANVIEN.PHG = PHONGBAN.MAPHG 
	WHERE TENPHG like N'Nghiên Cứu'
)

--Bai 3
SELECT UPPER(HONV),TENLOT,TENNV,DCHI
	   FROM NHANVIEN JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
	   GROUP BY HONV,TENLOT,TENNV,DCHI
	   HAVING COUNT(THANNHAN.MA_NVIEN)>2

SELECT HONV,LOWER(TENLOT),TENNV,DCHI
	   FROM NHANVIEN JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
	   GROUP BY HONV,TENLOT,TENNV,DCHI
	   HAVING COUNT(THANNHAN.MA_NVIEN)>2

SELECT HONV,TENLOT,LEFT(TENNV,1)+UPPER(SUBSTRING(TENNV,2,1))+SUBSTRING(TENNV,3,LEN(TENNV)-2),DCHI
	   FROM NHANVIEN JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
	   GROUP BY HONV,TENLOT,TENNV,DCHI
	   HAVING COUNT(THANNHAN.MA_NVIEN)>2

SELECT HONV, TENLOT, TENNV, SUBSTRING(DCHI,CHARINDEX(' ',DCHI), CHARINDEX(',', DCHI)-4),DCHI
	FROM NHANVIEN
	JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
	GROUP BY HONV, TENLOT, TENNV, DCHI
	HAVING COUNT(THANNHAN.MA_NVIEN) > 2
 
DECLARE @max int;
SELECT TOP 1 @max = COUNT(MANV)
FROM PHONGBAN
JOIN NHANVIEN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY PHONGBAN.MAPHG
ORDER BY COUNT(MANV) DESC;

SELECT TENNV ='Fpoly'
FROM NHANVIEN
WHERE PHG IN (
    SELECT PHG
    FROM NHANVIEN
    GROUP BY PHG
    HAVING COUNT(PHG) = @max
);

--Bai 4
SELECT  * FROM NHANVIEN WHERE YEAR(NGSINH)>=1960 AND YEAR(NGSINH)<=1965
SELECT  *,YEAR(GETDATE())-YEAR(NGSINH)AS'Tuoi' FROM NHANVIEN 
SELECT *,DATENAME(weekday,NGSINH) FROM NHANVIEN
SELECT *,CONVERT(varchar,NGSINH,105) FROM NHANVIEN