USE QLDA;
-----Bai1
DECLARE @avgLuong table (maPhong int, luongTb float);
INSERT INTO @avgLuong
	SELECT PHG,AVG(LUONG) FROM NHANVIEN
		GROUP BY PHG;
SELECT TENNV,LUONG,NhanGiaTri = case
	WHEN LUONG < luongTb THEN 'tang luong'
	ELSE 'Khong tang luong'
	END
FROM NHANVIEN JOIN @avgLuong ON NHANVIEN.PHG = maPhong;

SELECT TENNV,LUONG,ChucVu = case
	WHEN LUONG < luongTb THEN 'Nhan Vien'
	ELSE 'Truong Phong'
	END
FROM NHANVIEN JOIN @avgLuong ON NHANVIEN.PHG = maPhong;
GO
SELECT TENNV = case PHAI
	WHEN N'Nam' THEN 'MR '+[TENNV]
	Else 'Mrs'+[TENNV]
	END
FROM NHANVIEN;
GO 
SELECT TENNV,LUONG,
Thue=CASE 
	WHEN LUONG BETWEEN 0 AND 25000 THEN LUONG*0.1
	WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG*0.12
	WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG*0.15
	WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG*0.1
	WHEN LUONG > 50000 THEN LUONG *0.25
END
FROM NHANVIEN
--Bai2
--SELECT TENNV,MANV FROM NHANVIEN WHERE CONVERT(int,MANV) % 2 = 0; =))))))))
DECLARE @i int = 2;
DECLARE @slNhanVien int;
SELECT @slNhanVien =COUNT(MANV) FROM NHANVIEN
	
	WHILE @i<@slNhanVien
		BEGIN
			SELECT TENNV,MANV FROM NHANVIEN WHERE CONVERT(int,MANV) = @i ;
			SET @i = @i+2;
		END;
